name: Your Life Matters
favicon: null
layout_spectrum: 0.44267775514163077
typography_spectrum: 0.16568849934265018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfcdd8'
    - '#1d1417'
    - '#803575'
    - '#d39b84'
    - '#756e76'
  brandStrength: 0.5928194816224277
  lightness: 0.6316838720813394
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
